services:
  - type: web
    name: premios-flask
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn premios:app
    envVars:
      PYTHON_VERSION: 3.10
